//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NG2Sample
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_hero
    {
        public int heroId { get; set; }
        public string heroName { get; set; }
        public string realName { get; set; }
        public string heroStrength { get; set; }
        public string heroNature { get; set; }
        public string ImageUrl { get; set; }
    }
}
